# 207 — BaseAgent
Verifies the abstract base class mechanics: construction, `log_tool_event`,
`log_decision_event`, and `generate_ai_summary` — using a `DummyAgent` subclass
against a real Neo4j-backed trace.

In [1]:
import sys
sys.path.insert(0, "..")

In [2]:
import uuid
import logging
import pandas as pd

from src.config import get_neo4j_settings
from src.storage.neo4j_repository import Neo4jRepository
from src.storage.trace_repository import TraceRepository
from src.tracing.trace_service import TraceService
from src.tools.trace_tools import TraceTools
from src.agents.base import BaseAgent
from src.domain.models import (
    AgentResult,
    InvestigationRequest,
    InvestigationTrace,
    UserContext,
)

# Route agent.* logs to the notebook console so we can see the debug lines.
logging.basicConfig(level=logging.DEBUG, format="%(name)-30s %(levelname)-8s %(message)s")

settings = get_neo4j_settings()
neo4j    = Neo4jRepository(**vars(settings))
neo4j.test_connection()

repo    = TraceRepository(neo4j)
service = TraceService(repo)
tools   = TraceTools(repo)
print("Connected")

neo4j.pool                     DEBUG    [#0000]  _: <POOL> created, routing address IPv4Address(('ef39cb3b.databases.neo4j.io', 7687))
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> resolve home database
neo4j.pool                     DEBUG    [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('ef39cb3b.databases.neo4j.io', 7687))
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: ef39cb3b.databases.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.pool                     DEBUG    [#0000]  _: <POOL> _acquire router connection, database=None, address=ResolvedIPv4Address(('35.244.112.230', 7687))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> trying to hand out new connection
neo4j.io                       DEBUG    [#0000]  C: <OPEN> 35.244.112.230:7687
neo4j.io                       DEBUG    [#C072]  C: <SECURE> ef39cb3b.databases.neo4j.io
neo4j.io                       DEBUG    [#C072]  C: <MAGIC> 0x6060B017
neo4j.io                       DEBUG    [#C072]  C: <HANDSHAKE> 0x000001FF 0x00080805 0x00020404 0x00000003
neo4j.io                       DEBUG    [#C072]  S: <HANDSHAKE> 0x000001FF [4] 0x00040404 0x00040405 0x00020805 0x00000006 0x00
neo4j.io                       DEBUG    [#C072]  C: <HANDSHAKE> 0x00000006 0x00
neo4j.io                       DEBUG    [#C072]  C: HELLO {'user_agent': 'neo4j-python/6.1.0 Python/3.11.13-final-0 (darwin)', 'routing': {'address': 'ef39cb3b.databases.neo4j.io:7687'}, 'bolt_agent': {'product': 'neo4j-python/6.1.0', 'platform': 'Darwin 25.3.0; x86_64', 'language': 'Python/3.11.13-final-0', 'language_details': 'CPython; 3.11.13-final-0 (main, Jun  5 2025 08:14:07) [Clang 14.0.6 ]'}}
neo4j.io                       DEBUG    [#C072]  _: <CONNECTION> client state: CONNECTED > AUTHENTICATION
neo4j.io                       DEBUG    [#C072]  C: LOGON {'scheme': 'basic', 'principal': 'neo4j', 'credentials': '*******'}
neo4j.io                       DEBUG    [#C072]  _: <CONNECTION> client state: AUTHENTICATION > READY
neo4j.io                       DEBUG    [#C072]  S: SUCCESS {'server': 'Neo4j/5.27-aura', 'protocol_version': '6.0', 'connection_id': 'bolt-897', 'hints': {'connection.recv_timeout_seconds': 60, 'ssr.enabled': True}}
neo4j.io                       DEBUG    [#C072]  _: <CONNECTION> server state: CONNECTED > AUTHENTICATION
neo4j.io                       DEBUG    [#C072]  S: SUCCESS {'advertised_address': 'p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'}
neo4j.io                       DEBUG    [#C072]  _: <CONNECTION> server state: AUTHENTICATION > READY
neo4j.io                       DEBUG    [#C072]  C: ROUTE {'address': 'ef39cb3b.databases.neo4j.io:7687'} () {}
neo4j.io                       DEBUG    [#C072]  S: SUCCESS {'rt': {'servers': [{'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'WRITE'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'READ'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'ROUTE'}], 'ttl': 10, 'db': 'neo4j'}}
neo4j.pool                     DEBUG    [#C072]  _: <POOL> released bolt-897
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> updated table=RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34700.39359025, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> update routing table from address=ResolvedIPv4Address(('35.244.112.230', 7687)) (RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34700.39359025, ttl=10))
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='READ', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34700.39359025, ttl=10, perf_time=34700.39570125 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=True): table expired=False, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => True
neo4j.pool                     DEBUG    [#0000]  _: <POOL> using existing routing table RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34700.39359025, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> trying to hand out new connection
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.io                       DEBUG    [#0000]  C: <OPEN> 35.244.112.230:7687
neo4j.io                       DEBUG    [#C073]  C: <SECURE> p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io
neo4j.io                       DEBUG    [#C073]  C: <MAGIC> 0x6060B017
neo4j.io                       DEBUG    [#C073]  C: <HANDSHAKE> 0x000001FF 0x00080805 0x00020404 0x00000003
neo4j.io                       DEBUG    [#C073]  S: <HANDSHAKE> 0x000001FF [4] 0x00040404 0x00040405 0x00020805 0x00000006 0x00
neo4j.io                       DEBUG    [#C073]  C: <HANDSHAKE> 0x00000006 0x00
neo4j.io                       DEBUG    [#C073]  C: HELLO {'user_agent': 'neo4j-python/6.1.0 Python/3.11.13-final-0 (darwin)', 'routing': {'address': 'ef39cb3b.databases.neo4j.io:7687'}, 'bolt_agent': {'product': 'neo4j-python/6.1.0', 'platform': 'Darwin 25.3.0; x86_64', 'language': 'Python/3.11.13-final-0', 'language_details': 'CPython; 3.11.13-final-0 (main, Jun  5 2025 08:14:07) [Clang 14.0.6 ]'}}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> client state: CONNECTED > AUTHENTICATION
neo4j.io                       DEBUG    [#C073]  C: LOGON {'scheme': 'basic', 'principal': 'neo4j', 'credentials': '*******'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> client state: AUTHENTICATION > READY
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'server': 'Neo4j/5.27-aura', 'protocol_version': '6.0', 'connection_id': 'bolt-898', 'hints': {'connection.recv_timeout_seconds': 60, 'ssr.enabled': True}}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: CONNECTED > AUTHENTICATION
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'advertised_address': 'p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: AUTHENTICATION > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898

Connected

## Define DummyAgent

`DummyAgent` is the minimal concrete subclass — it implements the required
`run()` method and delegates everything else to `BaseAgent`.
Real agents (`GraphAgent`, `RiskAgent`, `TraceAgent`) follow exactly this
pattern.

In [3]:
class DummyAgent(BaseAgent):
    """Minimal concrete agent used to verify BaseAgent mechanics."""

    def run(
        self,
        task: str,
        context: dict,
        trace: InvestigationTrace,
    ) -> AgentResult:
        company = context.get("company_name", "unknown")

        # 1. Log a routing decision before doing any work.
        self.log_decision_event(
            trace,
            decision=f"Starting task '{task}' for {company}",
            why="entry point of DummyAgent.run",
        )

        # 2. Simulate calling a tool and logging the result.
        self.log_tool_event(
            trace,
            tool_name="dummy_check",
            input_summary=f"company_name={company}",
            output_summary="risk_level=LOW (dummy result)",
            decision="no further steps required",
            why="DummyAgent always returns LOW risk",
            step_id="step_1",
            entity_refs=[{"label": "Company", "name": company}],
        )

        # 3. Optionally generate an AI narrative (None if no client).
        ai_text = self.generate_ai_summary(
            system_prompt="You are a risk analyst.",
            user_prompt=f"Summarise a LOW-risk finding for {company} in one sentence.",
        )

        summary = ai_text or f"{company}: LOW risk (AI unavailable — no summary generated)."

        return AgentResult(
            request_id=trace.request_id,
            entity_name=company,
            success=True,
            summary=summary,
            findings={"risk_level": "LOW"},
            trace=trace,
        )


print("DummyAgent defined")

DummyAgent defined

## Verify BaseAgent is abstract

Instantiating `BaseAgent` directly must raise `TypeError`.

In [4]:
try:
    BaseAgent("should-fail", service)  # type: ignore[abstract]
    print("ERROR — BaseAgent should not be instantiable")
except TypeError as exc:
    print(f"✓ BaseAgent is abstract: {exc}")

✓ BaseAgent is abstract: Can't instantiate abstract class BaseAgent with abstract method run

## Instantiate DummyAgent — without AI client

In [5]:
agent = DummyAgent(name="dummy-agent", trace_service=service)
print(f"agent.name       : {agent.name}")
print(f"agent._ai_client : {agent._ai_client}")
print(f"logger name      : {agent._log.name}")

agent.name       : dummy-agent
agent._ai_client : None
logger name      : agent.dummy-agent

## Start a trace, run the agent

In [6]:
request = InvestigationRequest(
    entity_name="TELEFONICA O2 HOLDINGS LIMITED",
    context=UserContext(
        user_id="analyst-001",
        session_id=str(uuid.uuid4()),
        metadata={"mode": "interactive"},
    ),
    request_id=str(uuid.uuid4()),
)

trace = service.start_trace(request, request.context)
print(f"trace_id: {trace.request_id}")

neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34700.39359025, ttl=10, perf_time=34710.485115875 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=True, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => False
neo4j.pool                     DEBUG    [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.pool                     DEBUG    [#0000]  _: <POOL> _acquire router connection, database='neo4j', address=ResolvedIPv4Address(('35.244.112.230', 7687))
neo4j.pool                     DEBUG    [#C072]  _: <POOL> picked existing connection bolt-897
neo4j.pool                     DEBUG    [#C072]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C072]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C072]  C: ROUTE {'address': 'ef39cb3b.databases.neo4j.io:7687'} () {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C072]  S: SUCCESS {'rt': {'servers': [{'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'WRITE'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'READ'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'ROUTE'}], 'ttl': 10, 'db': 'neo4j'}}
neo4j.pool                     DEBUG    [#C072]  _: <POOL> released bolt-897
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> updated table=RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34710.513358833, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> update routing table from address=ResolvedIPv4Address(('35.244.112.230', 7687)) (RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34710.513358833, ttl=10))
neo4j.io                       DEBUG    [#C072]  C: GOODBYE
neo4j.io                       DEBUG    [#C072]  C: <CLOSE>
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n            MERGE (t:InvestigationTrace {trace_id: $trace_id})\n            ON CREATE SET\n                t.mode        = $mode,\n                t.user_id     = $user_id,\n                t.query       = $query,\n                t.started_at  = $started_at,\n                t.ended_at    = null,\n                t.final_summary = null\n            ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d', 'mode': 'interactive', 'user_id': 'analyst-001', 'query': 'TELEFONICA O2 HOLDINGS LIMITED', 'started_at': '2026-03-22T03:01:53.881812+00:00'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> client state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 5, 'fields': []}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAupA=', 'stats': {'contains-updates': True, 'labels-added': 1, 'nodes-created': 1, 'properties-set': 7}, 'statuses': [{'gql_status': '00001', 'status_description': 'note: successful completion - omitted result'}], 'type': 'w', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898

trace_id: 4cb03697-cf3c-4699-99ba-ba9ca5100e6d

In [7]:
result = agent.run(
    task="risk_check",
    context={"company_name": "TELEFONICA O2 HOLDINGS LIMITED"},
    trace=trace,
)
print(f"success : {result.success}")
print(f"summary : {result.summary}")
print(f"findings: {result.findings}")
print(f"in-memory events: {len(trace.events)}")

agent.dummy-agent              DEBUG    decision="Starting task 'risk_check' for TELEFONICA O2 HOLDINGS LIMITED" why='entry point of DummyAgent.run'
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34710.513358833, ttl=10, perf_time=34726.170385 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=True, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => False
neo4j.pool                     DEBUG    [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.pool                     DEBUG    [#0000]  _: <POOL> _acquire router connection, database='neo4j', address=ResolvedIPv4Address(('35.244.112.230', 7687))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> trying to hand out new connection
neo4j.io                       DEBUG    [#0000]  C: <OPEN> 35.244.112.230:7687
neo4j.io                       DEBUG    [#C081]  C: <SECURE> p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io
neo4j.io                       DEBUG    [#C081]  C: <MAGIC> 0x6060B017
neo4j.io                       DEBUG    [#C081]  C: <HANDSHAKE> 0x000001FF 0x00080805 0x00020404 0x00000003
neo4j.io                       DEBUG    [#C081]  S: <HANDSHAKE> 0x000001FF [4] 0x00040404 0x00040405 0x00020805 0x00000006 0x00
neo4j.io                       DEBUG    [#C081]  C: <HANDSHAKE> 0x00000006 0x00
neo4j.io                       DEBUG    [#C081]  C: HELLO {'user_agent': 'neo4j-python/6.1.0 Python/3.11.13-final-0 (darwin)', 'routing': {'address': 'ef39cb3b.databases.neo4j.io:7687'}, 'bolt_agent': {'product': 'neo4j-python/6.1.0', 'platform': 'Darwin 25.3.0; x86_64', 'language': 'Python/3.11.13-final-0', 'language_details': 'CPython; 3.11.13-final-0 (main, Jun  5 2025 08:14:07) [Clang 14.0.6 ]'}}
neo4j.io                       DEBUG    [#C081]  _: <CONNECTION> client state: CONNECTED > AUTHENTICATION
neo4j.io                       DEBUG    [#C081]  C: LOGON {'scheme': 'basic', 'principal': 'neo4j', 'credentials': '*******'}
neo4j.io                       DEBUG    [#C081]  _: <CONNECTION> client state: AUTHENTICATION > READY
neo4j.io                       DEBUG    [#C081]  S: SUCCESS {'server': 'Neo4j/5.27-aura', 'protocol_version': '6.0', 'connection_id': 'bolt-907', 'hints': {'connection.recv_timeout_seconds': 60, 'ssr.enabled': True}}
neo4j.io                       DEBUG    [#C081]  _: <CONNECTION> server state: CONNECTED > AUTHENTICATION
neo4j.io                       DEBUG    [#C081]  S: SUCCESS {'advertised_address': 'p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'}
neo4j.io                       DEBUG    [#C081]  _: <CONNECTION> server state: AUTHENTICATION > READY
neo4j.io                       DEBUG    [#C081]  C: ROUTE {'address': 'ef39cb3b.databases.neo4j.io:7687'} () {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C081]  S: SUCCESS {'rt': {'servers': [{'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'WRITE'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'READ'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'ROUTE'}], 'ttl': 10, 'db': 'neo4j'}}
neo4j.pool                     DEBUG    [#C081]  _: <POOL> released bolt-907
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> updated table=RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34726.275557917, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> update routing table from address=ResolvedIPv4Address(('35.244.112.230', 7687)) (RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34726.275557917, ttl=10))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n            MATCH (t:InvestigationTrace {trace_id: $trace_id})\n            OPTIONAL MATCH (t)-[:HAS_EVENT]->(existing:TraceEvent)\n            WITH t, count(existing) AS existing_count\n            CREATE (e:TraceEvent {\n                event_id:      $event_id,\n                event_number:  existing_count + 1,\n                event_type:    $event_type,\n                agent_name:    $agent_name,\n                tool_name:     $tool_name,\n                input_summary: $input_summary,\n                output_summary: $output_summary,\n                decision:      $decision,\n                why:           $why,\n                created_at:    $created_at\n            })\n            CREATE (t)-[:HAS_EVENT]->(e)\n            WITH t, e, existing_count\n            WHERE existing_count > 0\n            MATCH (t)-[:HAS_EVENT]->(prev:TraceEvent {event_number: existing_count})\n            CREATE (prev)-[:NEXT_EVENT]->(e)\n            ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d', 'event_id': 'e167221c-4e92-4797-bcb6-a15c6e9ed9ac', 'event_type': 'agent_reasoning', 'agent_name': 'dummy-agent', 'tool_name': '', 'input_summary': "Starting task 'risk_check' for TELEFONICA O2 HOLDINGS LIMITED", 'output_summary': '', 'decision': "Starting task 'risk_check' for TELEFONICA O2 HOLDINGS LIMITED", 'why': 'entry point of DummyAgent.run', 'created_at': '2026-03-22T03:02:09.567253+00:00'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 61, 'fields': []}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAu5A=', 'stats': {'contains-updates': True, 'labels-added': 1, 'relationships-created': 1, 'nodes-created': 1, 'properties-set': 10}, 'statuses': [{'gql_status': '00001', 'status_description': 'note: successful completion - omitted result'}], 'type': 'w', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898
agent.dummy-agent              DEBUG    tool_returned tool=dummy_check input='company_name=TELEFONICA O2 HOLDINGS LIMITED' output='risk_level=LOW (dummy result)' decision='no further steps required'
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34726.275557917, ttl=10, perf_time=34726.364947 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=False, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => True
neo4j.pool                     DEBUG    [#0000]  _: <POOL> using existing routing table RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34726.275557917, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n            MATCH (t:InvestigationTrace {trace_id: $trace_id})\n            OPTIONAL MATCH (t)-[:HAS_EVENT]->(existing:TraceEvent)\n            WITH t, count(existing) AS existing_count\n            CREATE (e:TraceEvent {\n                event_id:      $event_id,\n                event_number:  existing_count + 1,\n                event_type:    $event_type,\n                agent_name:    $agent_name,\n                tool_name:     $tool_name,\n                input_summary: $input_summary,\n                output_summary: $output_summary,\n                decision:      $decision,\n                why:           $why,\n                created_at:    $created_at\n            })\n            CREATE (t)-[:HAS_EVENT]->(e)\n            WITH t, e, existing_count\n            WHERE existing_count > 0\n            MATCH (t)-[:HAS_EVENT]->(prev:TraceEvent {event_number: existing_count})\n            CREATE (prev)-[:NEXT_EVENT]->(e)\n            ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d', 'event_id': '101c3983-de11-480e-837a-4dc72976fea8', 'event_type': 'tool_returned', 'agent_name': 'dummy-agent', 'tool_name': 'dummy_check', 'input_summary': 'company_name=TELEFONICA O2 HOLDINGS LIMITED', 'output_summary': 'risk_level=LOW (dummy result)', 'decision': 'no further steps required', 'why': 'DummyAgent always returns LOW risk', 'created_at': '2026-03-22T03:02:09.762427+00:00'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 59, 'fields': []}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAvJA=', 'stats': {'contains-updates': True, 'labels-added': 1, 'relationships-created': 2, 'nodes-created': 1, 'properties-set': 10}, 'statuses': [{'gql_status': '00001', 'status_description': 'note: successful completion - omitted result'}], 'type': 'w', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34726.275557917, ttl=10, perf_time=34726.452371917 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=False, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => True
neo4j.pool                     DEBUG    [#0000]  _: <POOL> using existing routing table RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34726.275557917, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n            MATCH (e:TraceEvent {event_id: $event_id})\n            MATCH (n:`Company` {name: $value})\n            MERGE (e)-[:ABOUT]->(n)\n            ' {'event_id': '101c3983-de11-480e-837a-4dc72976fea8', 'value': 'TELEFONICA O2 HOLDINGS LIMITED'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 4, 'fields': []}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAvZA=', 'stats': {'contains-updates': True, 'relationships-created': 1}, 'statuses': [{'gql_status': '00001', 'status_description': 'note: successful completion - omitted result'}], 'type': 'w', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898
agent.dummy-agent              DEBUG    generate_ai_summary skipped — no ai_client configured

success : True
summary : TELEFONICA O2 HOLDINGS LIMITED: LOW risk (AI unavailable — no summary generated).
findings: {'risk_level': 'LOW'}
in-memory events: 2

## Finalize and retrieve

In [8]:
service.finalize_trace(trace, final_summary=result.summary)

r = tools.retrieve_trace(trace.request_id)
print(f"[{'✓' if r.success else '✗'}] {r.tool_name}  ({r.duration_ms} ms)")
print(f"    {r.summary}")
if r.data:
    print(f"\nfinal_summary: {r.data['final_summary']}")
    print("\nEvents:")
    events_df = pd.DataFrame(r.data["events"])
    display(events_df[["event_number", "event_type", "agent_name", "tool_name", "input_summary", "output_summary", "decision"]])

neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34726.275557917, ttl=10, perf_time=34744.394951375 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=True, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => False
neo4j.pool                     DEBUG    [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.pool                     DEBUG    [#0000]  _: <POOL> _acquire router connection, database='neo4j', address=ResolvedIPv4Address(('35.244.112.230', 7687))
neo4j.pool                     DEBUG    [#C081]  _: <POOL> picked existing connection bolt-907
neo4j.pool                     DEBUG    [#C081]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C081]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C081]  C: ROUTE {'address': 'ef39cb3b.databases.neo4j.io:7687'} () {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C081]  S: SUCCESS {'rt': {'servers': [{'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'WRITE'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'READ'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'ROUTE'}], 'ttl': 10, 'db': 'neo4j'}}
neo4j.pool                     DEBUG    [#C081]  _: <POOL> released bolt-907
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> updated table=RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34744.419204167, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> update routing table from address=ResolvedIPv4Address(('35.244.112.230', 7687)) (RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34744.419204167, ttl=10))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n            MATCH (t:InvestigationTrace {trace_id: $trace_id})\n            SET t.ended_at      = $ended_at,\n                t.final_summary = $final_summary\n            ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d', 'ended_at': '2026-03-22T03:02:27.791611+00:00', 'final_summary': 'TELEFONICA O2 HOLDINGS LIMITED: LOW risk (AI unavailable — no summary generated).'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 19, 'fields': []}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAvpA=', 'stats': {'contains-updates': True, 'properties-set': 2}, 'statuses': [{'gql_status': '00001', 'status_description': 'note: successful completion - omitted result'}], 'type': 'w', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34744.419204167, ttl=10, perf_time=34744.465521208 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=False, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => True
neo4j.pool                     DEBUG    [#0000]  _: <POOL> using existing routing table RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34744.419204167, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n            MATCH (t:InvestigationTrace {trace_id: $trace_id})\n            RETURN\n                t.trace_id       AS trace_id,\n                t.query          AS query,\n                t.user_id        AS user_id,\n                t.mode           AS mode,\n                t.started_at     AS started_at,\n                t.ended_at       AS ended_at,\n                t.final_summary  AS final_summary\n            ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 2, 'fields': ['trace_id', 'query', 'user_id', 'mode', 'started_at', 'ended_at', 'final_summary']}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: RECORD * 1
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAvpA=', 'statuses': [{'gql_status': '00000', 'status_description': 'note: successful completion'}], 'type': 'r', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34744.419204167, ttl=10, perf_time=34744.488779875 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=False, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => True
neo4j.pool                     DEBUG    [#0000]  _: <POOL> using existing routing table RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34744.419204167, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN "\n            MATCH (t:InvestigationTrace {trace_id: $trace_id})-[:HAS_EVENT]->(e:TraceEvent)\n            OPTIONAL MATCH (e)-[:ABOUT]->(n)\n            RETURN\n                e.event_number   AS event_number,\n                e.event_id       AS event_id,\n                e.event_type     AS event_type,\n                e.agent_name     AS agent_name,\n                e.tool_name      AS tool_name,\n                e.input_summary  AS input_summary,\n                e.output_summary AS output_summary,\n                e.decision       AS decision,\n                e.why            AS why,\n                e.created_at     AS created_at,\n                collect(DISTINCT {\n                    labels: labels(n),\n                    identifier: coalesce(n.name, n.code, n.postal_code, '')\n                }) AS about\n            ORDER BY e.event_number\n            " {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 1, 'fields': ['event_number', 'event_id', 'event_type', 'agent_name', 'tool_name', 'input_summary', 'output_summary', 'decision', 'why', 'created_at', 'about']}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: RECORD * 1
neo4j.io                       DEBUG    [#C073]  S: RECORD * 1
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAvpA=', 'statuses': [{'gql_status': '00000', 'status_description': 'note: successful completion'}], 'type': 'r', 't_last': 1, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898

[✓] retrieve_trace  (47.2 ms)
    Trace '4cb03697-cf3c-4699-99ba-ba9ca5100e6d' for 'TELEFONICA O2 HOLDINGS LIMITED': 2 event(s).

final_summary: TELEFONICA O2 HOLDINGS LIMITED: LOW risk (AI unavailable — no summary generated).

Events:

,event_number,event_type,agent_name,tool_name,input_summary,output_summary,decision
0,1,agent_reasoning,dummy-agent,,Starting task 'risk_check' for TELEFONICA O2 H...,,Starting task 'risk_check' for TELEFONICA O2 H...
1,2,tool_returned,dummy-agent,dummy_check,company_name=TELEFONICA O2 HOLDINGS LIMITED,risk_level=LOW (dummy result),no further steps required

## Verify generate_ai_summary — without AI client

`generate_ai_summary` must return `None` silently when no client is set.

In [9]:
result_no_ai = agent.generate_ai_summary(
    system_prompt="You are a risk analyst.",
    user_prompt="Summarise the risk for TELEFONICA O2 HOLDINGS LIMITED.",
)
assert result_no_ai is None, "Expected None when ai_client is not set"
print("✓ generate_ai_summary returns None when ai_client is None")

agent.dummy-agent              DEBUG    generate_ai_summary skipped — no ai_client configured

✓ generate_ai_summary returns None when ai_client is None

## Verify agent_name is stored on Neo4j TraceEvent nodes

The `agent_name` column should read `"dummy-agent"` for every event
written by this agent.

In [10]:
rows = neo4j.run_query(
    """
    MATCH (t:InvestigationTrace {trace_id: $trace_id})-[:HAS_EVENT]->(e:TraceEvent)
    RETURN e.event_number AS event_number, e.event_type AS event_type,
           e.agent_name  AS agent_name
    ORDER BY e.event_number
    """,
    {"trace_id": trace.request_id},
)
display(pd.DataFrame(rows))

neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34744.419204167, ttl=10, perf_time=34757.951266292 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=True, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => False
neo4j.pool                     DEBUG    [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.pool                     DEBUG    [#0000]  _: <POOL> _acquire router connection, database='neo4j', address=ResolvedIPv4Address(('35.244.112.230', 7687))
neo4j.pool                     DEBUG    [#C081]  _: <POOL> picked existing connection bolt-907
neo4j.pool                     DEBUG    [#C081]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C081]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C081]  C: ROUTE {'address': 'ef39cb3b.databases.neo4j.io:7687'} () {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C081]  S: SUCCESS {'rt': {'servers': [{'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'WRITE'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'READ'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'ROUTE'}], 'ttl': 10, 'db': 'neo4j'}}
neo4j.pool                     DEBUG    [#C081]  _: <POOL> released bolt-907
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> updated table=RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34757.973872208, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> update routing table from address=ResolvedIPv4Address(('35.244.112.230', 7687)) (RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34757.973872208, ttl=10))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n    MATCH (t:InvestigationTrace {trace_id: $trace_id})-[:HAS_EVENT]->(e:TraceEvent)\n    RETURN e.event_number AS event_number, e.event_type AS event_type,\n           e.agent_name  AS agent_name\n    ORDER BY e.event_number\n    ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 48, 'fields': ['event_number', 'event_type', 'agent_name']}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: RECORD * 1
neo4j.io                       DEBUG    [#C073]  S: RECORD * 1
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAvpA=', 'statuses': [{'gql_status': '00000', 'status_description': 'note: successful completion'}], 'type': 'r', 't_last': 1, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898

   event_number       event_type   agent_name
0             1  agent_reasoning  dummy-agent
1             2    tool_returned  dummy-agent

## Cleanup — delete this notebook's trace from Neo4j

In [11]:
neo4j.run_query(
    """
    MATCH (t:InvestigationTrace {trace_id: $trace_id})
    OPTIONAL MATCH (t)-[:HAS_EVENT]->(e:TraceEvent)
    DETACH DELETE t, e
    """,
    {"trace_id": trace.request_id},
)
print(f"Deleted trace {trace.request_id} and its events")

neo4j                          DEBUG    [#0000]  _: <WORKSPACE> routing towards fixed database: neo4j
neo4j                          DEBUG    [#0000]  _: <WORKSPACE> pinning database: 'neo4j'
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire routing connection, access_mode='WRITE', database=AcquisitionDatabase(name='neo4j', guessed=False)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> routing aged?, database=neo4j
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> purge check: last_updated_time=34757.973872208, ttl=10, perf_time=34775.624707125 => False
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> checking table freshness (readonly=False): table expired=True, has_server_for_mode=True, table routers=OrderedSet((IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)))) => False
neo4j.pool                     DEBUG    [#0000]  _: <POOL> attempting to update routing table from IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> in: p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687
neo4j.io                       DEBUG    [#0000]  _: <RESOLVE> dns resolver out: 35.244.112.230:7687
neo4j.pool                     DEBUG    [#0000]  _: <POOL> _acquire router connection, database='neo4j', address=ResolvedIPv4Address(('35.244.112.230', 7687))
neo4j.pool                     DEBUG    [#C081]  _: <POOL> picked existing connection bolt-907
neo4j.pool                     DEBUG    [#C081]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C081]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C081]  C: ROUTE {'address': 'ef39cb3b.databases.neo4j.io:7687'} () {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C081]  S: SUCCESS {'rt': {'servers': [{'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'WRITE'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'READ'}, {'addresses': ['p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io:7687'], 'role': 'ROUTE'}], 'ttl': 10, 'db': 'neo4j'}}
neo4j.pool                     DEBUG    [#C081]  _: <POOL> released bolt-907
neo4j.pool                     DEBUG    [#0000]  _: <ROUTING> updated table=RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34775.646503667, ttl=10)
neo4j.pool                     DEBUG    [#0000]  _: <POOL> update routing table from address=ResolvedIPv4Address(('35.244.112.230', 7687)) (RoutingTable(database='neo4j', routers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), readers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), writers=(IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687)),), last_updated_time=34775.646503667, ttl=10))
neo4j.pool                     DEBUG    [#0000]  _: <POOL> acquire address, database='neo4j' address=IPv4Address(('p-ef39cb3b-a2ee-0003.production-orch-1243.neo4j.io', 7687))
neo4j.pool                     DEBUG    [#C073]  _: <POOL> picked existing connection bolt-898
neo4j.pool                     DEBUG    [#C073]  _: <POOL> checked re_auth auth=None updated=False force=False
neo4j.pool                     DEBUG    [#C073]  _: <POOL> handing out existing connection
neo4j.io                       DEBUG    [#C073]  C: RUN '\n    MATCH (t:InvestigationTrace {trace_id: $trace_id})\n    OPTIONAL MATCH (t)-[:HAS_EVENT]->(e:TraceEvent)\n    DETACH DELETE t, e\n    ' {'trace_id': '4cb03697-cf3c-4699-99ba-ba9ca5100e6d'} {'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  C: PULL {'n': 1000}
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'t_first': 3, 'fields': []}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: READY > STREAMING
neo4j.io                       DEBUG    [#C073]  S: SUCCESS {'bookmark': 'FB:kcwQ+2qFwnrlSpCOZEBTrnkWl8lAv5A=', 'stats': {'contains-updates': True, 'nodes-deleted': 3, 'relationships-deleted': 4}, 'statuses': [{'gql_status': '00001', 'status_description': 'note: successful completion - omitted result'}], 'type': 'w', 't_last': 0, 'db': 'neo4j'}
neo4j.io                       DEBUG    [#C073]  _: <CONNECTION> server state: STREAMING > READY
neo4j.pool                     DEBUG    [#C073]  _: <POOL> released bolt-898

Deleted trace 4cb03697-cf3c-4699-99ba-ba9ca5100e6d and its events

In [12]:
neo4j.close()
print("Driver closed")

neo4j.pool                     DEBUG    [#0000]  _: <POOL> close
neo4j.io                       DEBUG    [#C073]  C: GOODBYE
neo4j.io                       DEBUG    [#C073]  C: <CLOSE>
neo4j.io                       DEBUG    [#C081]  C: GOODBYE
neo4j.io                       DEBUG    [#C081]  C: <CLOSE>

Driver closed